/**
 * Class Main -- program entry point
 * 
 * Copyright 2011 Jan Minar <rdancer@rdancer.org>  All rights reserved.
 *
 * @author Jan Minar <rdancer@rdancer.org> 
 *
 * 
 * Usage: java Main <INPUT_DATA_FILE> > <OUTPUT_DATA_FILE>
 *
 */

import java.io.*;

public class Main
{
    /**
     * Constructor for objects of class Main
     */
    public Main()
    {
        // Constructor stub generated by BlueJ    
    }

    public static void main(String[] args)
            throws Exception
    {
        World world = new World(new File(args[0])); // do not check; this is throw-away code
        Solver solver = new NullSolver(world);
        solver.start();
        System.out.print(solver.getBestTour().toString());
    }
}
