/**
 * The test class NullSolverTest.  Generated by BlueJ.
 *
 * Copyright BlueJ authors
 * Copyright 2011 Jan Minar <rdancer@rdancer.org>  All rights reserved.
 *
 * @author BlueJ authors
 * @author Jan Minar <rdancer@rdancer.org> 
 */

import java.util.*;

public class NullSolverTest extends junit.framework.TestCase
{
    private String sampleInputDataFileContents;
    private int cityCount = 8;
    
    /**
     * Default constructor for test class NullSolverTest
     */
    public NullSolverTest()
    {
    }

    protected void setUp()
    {
       String s = "NAME = testcase,\n";
       s += "SIZE = 8,\n";
       s += "2,6,8,9,8,6,3,\n";
       s += "4,8,10,10,7,5,\n";
       s += "5,6,8,8,9,\n";
       s += "4,6,7,8,\n";
       s += "3,5,9,\n";
       s += "3,6,\n";
       s += "4\n";
        
       sampleInputDataFileContents = s;
    }
    
    public void testSolveSimple()
            throws Exception
    {
        Solver nullSolver = new NullSolver(new World(sampleInputDataFileContents));
        
        List<Integer> path = nullSolver.getBestTour().getPath();
        
        assert(path.size() == cityCount);
        
        //System.out.println(nullSolver.getBestTour());
    }

    /**
     * Tears down the test fixture.
     *
     * Called after every test case method.
     */
    protected void tearDown()
    {
    }
}
