/**
 * The test class WorldTest.  Generated by BlueJ.
 *
 * Copyright BlueJ authors
 * Copyright 2011 Jan Minar <rdancer@rdancer.org>  All rights reserved.
 *
 * @author BlueJ authors
 * @author Jan Minar <rdancer@rdancer.org> 
 */

import java.io.*;


public class WorldTest extends junit.framework.TestCase
{
    private String sampleInputDataFileContents;
    private int cityCount = 8;
        
    /**
     * Default constructor for test class WorldTest
     */
    public WorldTest()
    {
    }

    /**
     * Sets up the test fixture.
     *
     * Called before every test case method.
     */
    protected void setUp()
    {
       String s = "NAME = testcase,\n";
       s += "SIZE = 8,\n";
       s += "2,6,8,9,8,6,3,\n";
       s += "4,8,10,10,7,5,\n";
       s += "5,6,8,8,9,\n";
       s += "4,6,7,8,\n";
       s += "3,5,9,\n";
       s += "3,6,\n";
       s += "4\n";
        
       sampleInputDataFileContents = s;
    }

    /**
     * Tears down the test fixture.
     *
     * Called after every test case method.
     */
    protected void tearDown()
    {
    }
    
    
    public void testNewWorldFromString()
            throws Exception
    {
        World myWorld = new World(sampleInputDataFileContents);
        
        assert(myWorld.cityCount() == cityCount);
        assert(myWorld.toString().equals(sampleInputDataFileContents));
    }  
    
    public void testNewWorldFromFile()
            throws Exception
    {
        World myWorld = new World(new File("assignment/testcase.txt"));
                
        assert(myWorld.cityCount() == cityCount);
        assert(myWorld.toString().equals(sampleInputDataFileContents));
    }

}
